### ISSUE TITLE
Add support for days in future months

### ISSUE THREAD

**Issue by dangothemango** [dangothemango/epic-reservations#2]
change the format of desiredDay(s) to be 'mm/dd' if the day is in a month that is not the current month, automatically move the calendar to the specified month.

**Comment by bcs215** [comment]
Curious to see when this feature gets pushed, any thoughts on an ETA or if you need any collab on the enhancement? Lmk

**Comment by dangothemango** [comment]
@bcs215 wasnt a top priority for me until week of reservations were next month. ill look into it today

**Comment by dangothemango** [comment]
@bcs215 if you want to take it on though be my guest, just make sure to create a PR with the change

**Comment by bcs215** [comment]
@dangothemango If you have some time today go for it, I tried editing your timeout script locally but having trouble incorporating the change month functionality so if you have a working solution then I'd defer to you

**Comment by dangothemango** [comment]
@bcs215 sure thing, id say EOD or early tomorrow

**Comment by dangothemango** [comment]
@bcs215 this has been completed in commit https://github.com/dangothemango/epic-reservations/commit/fa3a989508c3589fe65c0810678b2398bfccf3b6

**Comment by bcs215** [comment]
@dangothemango script found the available day in January but failed to book it through the script and I had to manually book, can you take a look?

**Comment by dangothemango** [comment]
@bcs215 was there an error displayed?

**Comment by bcs215** [comment]
@dangothemango No error, the script just stopped executing on the last page - the one that gets displayed after selecting the pass holder checkbox and clicking the button.

**Comment by dangothemango** [comment]
@bcs215 when you were using it, were you trying to reserve multiple days at the same time? which days?

**Comment by bcs215** [comment]
@dangothemango I had just configured 1 day in the array, ['1/1']

**Comment by dangothemango** [comment]
@bcs215 ok, I think i found the issue. it seems to be that the checkbox for terms and conditions is sometimes appearing after the script tries to check it. it doesnt have to do with multi month support. I will attempt to correct it anyway. Thanks for calling it out

**Comment by dangothemango** [comment]
@bcs215 for now I added an additional wait call before it tries to check the box. the extra tenth of a second should allow for the terms and conditions checkbox to initialize before the script attempts to check it

**Comment by bcs215** [comment]
@dangothemango awesome, I'll give it a whirl and see how it performs. thanks for the quick fix

**Comment by bcs215** [comment]
@dangothemango confirmed working, thanks!
