### ISSUE TITLE
Setup handling of session timeouts

### ISSUE THREAD

**Issue by dangothemango** [dangothemango/epic-reservations#3]
After a certain amount of time, a popup appears that says your session will timeout in 10 minutes. A simple click event does not suffice for dismissing this popup. Figure out a way to extend the session using react events

**Comment by scottmsilver** [comment]
https://gist.github.com/scottmsilver/3ff9cff38445a8caa3c1e7781a93f286 seems to work.

**Comment by dangothemango** [comment]
@scottmsilver Sweet! if you want to make a PR ill approve it. otherwise ill do this at some point

**Comment by sbeemiller** [comment]
@dangothemango & @scottmsilver you guys are awesome for writing this thing!  Think it's going to save my butt into getting in to PC for some powder this weekend :).  I got the session dialogue timeout running the original script tonight and have just been clicking it away for now... @scottmsilver where do you add in the lines you wrote in https://gist.github.com/scottmsilver/3ff9cff38445a8caa3c1e7781a93f286 to get the dialogue box to go away?  Thanks much for the help!

**Comment by dangothemango** [comment]
@sbeemiller @scottmsilver Added the session extenstion code to the script in https://github.com/dangothemango/epic-reservations/commit/5b6cbbb3cfcd0afec47a63f0fcc3b019c6e71b79

**Comment by sbeemiller** [comment]
You two are legends... Thank you!
