### ISSUE TITLE
Question: which script is better to use?

### ISSUE THREAD

**Issue by isa3bel** [dangothemango/epic-reservations#6]
Hello, I'm interested in using these scripts (thank you for coding them up!). Is there a benefit for using one script over the other? The timeout seems simplest (at least to understand code-wise), but not sure if the other one is better to use for a specific scenario? Thanks!

**Comment by dangothemango** [comment]
Hi there,

I personally only use the Async script as it has had new features added to it like support for multiple days. the important difference is that the timeout script is slower so it is not as efficient. that said it is less likely to flag you for DDoSing epicpass.com

**Comment by isa3bel** [comment]
awesome thank you! And to test that it works, I should get an emailing confirming my reservation and that I secured a day? Once I found a reservation, will the script stop searching? Thanks again

**Comment by dangothemango** [comment]
Yep if it finds availability it will reserve the day and you will get an
email.

**Comment by isa3bel** [comment]
will the script stop searching after finding a reservation? I'm a developer and find your script really cool, it's a good learning experience to read your code and see what it's doing. I may try to contribute and make a PR. how long did it take you to make it?

**Comment by dangothemango** [comment]
Yea it does stop searching when it finds a reservation. When you return to
your computer it will have placed you on the reservation confirmation page.
Feel free to fork and contribute just make sure you PR any improvements or
changes you make. All in all I’ve probably spent like 5 hours on it.
