### ISSUE TITLE
Error When Running Script 

### ISSUE THREAD

**Issue by brookefishback** [dangothemango/epic-reservations#8]
VM674:81 Uncaught (in promise) TypeError: Illegal invocation
    at changeMountain (<anonymous>:81:26)
    at doTheWork (<anonymous>:205:8)
    at start (<anonymous>:220:2)
    at <anonymous>:1:1
    
    Hi Dan! I am getting the above error when attempting to run, here are the values I input. LMK if I am doing something wrong. Thanks!

desiredDay = "20"
mountains = ['14']
people = ['timothy reuber']
delay = 2000

**Comment by dangothemango** [comment]
Hey @brookefishback which script are you using?

**Comment by dangothemango** [comment]
Also @brookefishback what step was it on when it failed? like did you run the start command and it failed immediately or did it it work for a bit and then fail?

**Comment by brookefishback** [comment]
Got it figured out - TY!

**Comment by brookefishback** [comment]
BOOKED!! Wooo thank you so much! Lifesaver.

**Comment by dangothemango** [comment]
So glad it worked out!

**Comment by AndreyNokhrin** [comment]
Hi Dan! I have the same issue here

**Comment by AndreyNokhrin** [comment]
Uncaught (in promise) TypeError: Cannot read property 'disabled' of undefined
    at tryReserveDay (<anonymous>:194:21)
    at async doTheWork (<anonymous>:258:15)

**Comment by AndreyNokhrin** [comment]
it hasn't even started working yet. is it anything I can do about this problem? Thank you!

**Comment by dangothemango** [comment]
Andrew, can you please in as much detail as possible let me know what you
were doing. Also which script are you using and what do you have the
parameters set to?

**Comment by dangothemango** [comment]
Andrey*, sorry auto correct is a doozy

**Comment by AndreyNokhrin** [comment]
Hi Dan,
Thanks for the quick response.

I followed the instructions and launched the script for tomorrow in Park
City. I got this error:

Uncaught (in promise) TypeError: Cannot read property 'disabled' of
undefined
    at tryReserveDay (<anonymous>:194:21)
    at async doTheWork (<anonymous>:258:15)

Thanks a lot for your help!
Andrey

**Comment by dangothemango** [comment]
Can you just share with me the values you used for the desiredDays name and mountains variables

**Comment by AndreyNokhrin** [comment]
desiredDay = "20"
mountains = ['27']
people = ['andrey nokhrin']
delay = 2000

**Comment by AndreyNokhrin** [comment]
the script is timeout reservation

**Comment by AndreyNokhrin** [comment]
The script we were using is timeout reservation. Parameters: desiredDay =
“20”
Mountains = [27]
People =[‘andrey nokhrin’]
Delay = 2000

**Comment by dangothemango** [comment]
@AndreyNokhrin so park city is mountain 14. there is no mountain 27. I also reccomend you use the async script. as of recently it is more robust

**Comment by AndreyNokhrin** [comment]
Okay! Thank you very much! I will check it out right now

**Comment by AndreyNokhrin** [comment]
Thank you very much! It is working!

**Comment by dangothemango** [comment]
So glad! Let me know if you get a successful reservation. I love a success story :)
